platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

post_install do |installer|
    ## Fix for XCode 12.5 beta
    find_and_replace("../node_modules/react-native/React/CxxBridge/RCTCxxBridge.mm",
    "_initializeModules:(NSArray<id<RCTBridgeModule>> *)modules", "_initializeModules:(NSArray<Class> *)modules")
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
      text = File.read(name)
      replace = text.gsub(findstr,replacestr)
      if text != replace
          puts "Fix: " + name
          File.open(name, "w") { |file| file.puts replace }
          STDOUT.flush
      end
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

def pods
  # Pods for example
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'react-native-video', :path => '../node_modules/react-native-video/react-native-video.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNScreens', :path => '../node_modules/react-native-screens/RNScreens.podspec'
  use_native_modules!
end


target '2.2.1' do
  pods
end

target '2.3.1' do
  pods
end

target '2.3.3' do
  pods
end

target '2.4.1' do
  pods
end

target '2.4.2' do
  pods
end

target '3.1' do
  pods
end

target '3.1.2' do
  pods
end

target '3.2.1' do
  pods
end

target '3.2.2' do
  pods
end

target '3.3' do
  pods
end

target '3.4.1' do
  pods
end

target '4.1' do
  pods
end

target '4.2' do
  pods
end

target '4.3.1' do
  pods
end

target '4.3.2' do
  pods
end

target '5.1' do
  pods
end

target '5.1.1' do
  pods
end

target '5.1.3' do
  pods
end

target '5.2.1' do
  pods
end

target '5.2.2' do
  pods
end

target '5.3.3' do
  pods
end

target '5.5.1' do
  pods
end

target '6.1.1' do
  pods
end

target '6.1.1_custom' do
  pods
end

target '6.2.1' do
  pods
end

target '6.2.2' do
  pods
end

target '6.2.2_sequence' do
  pods
end

target '6.2.2_operation' do
  pods
end

target '6.3.2' do
  pods
end

target '7.1' do
  pods
end

target '8' do
  pods
end

target '9.2.1' do
  pods
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

target '9.3.1' do
  pods
#  pod 'ReactNativeNavigation', :podspec => '../node_modules/react-native-navigation/ReactNativeNavigation.podspec'
end


target '11.3' do
  pods
#  pod 'ReactNativeNavigation', :podspec => '../node_modules/react-native-navigation/ReactNativeNavigation.podspec'
end


target 'example' do
  pods
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'ReactNativeAudioToolkit', :path => '../node_modules/@react-native-community/audio-toolkit'
end


target 'example-tvOS' do
  # Pods for example-tvOS

  target 'example-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
